server:
  port: 8081

spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/demo
  #    driver-class-name: com.mysql.jdbc.Driver
  #    username: root
  #    password: 123456

  shardingsphere:
    datasource:
      names: common
      common:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/demo
        username: root
        password: 123456

